Repository paulsrijon/JavaScript_DSA, pull requests merged in 2022-10, with the labels that each got.

#6 Added recursive algorithms
  Recursive/BinaryEquivalent.js
  Recursive/BinarySearch.js
  Recursive/EucledianGCD.js
  Recursive/Factorial.js
  Recursive/FibonacciNumberRecursive.js
  Recursive/FloodFill.js
  Recursive/KochSnowflake.js
  Recursive/KochSnowflake.manual-test.js
  Recursive/Palindrome.js
  Recursive/SubsequenceRecursive.js
  Recursive/TowerOfHanoi.js
  Recursive/test/BinarySearch.test.js
  Recursive/test/Factorial.test.js
  Recursive/test/FibonacciNumberRecursive.test.js
  Recursive/test/FloodFill.test.js
  Recursive/test/KochSnowflake.test.js
  Recursive/test/palindrome.test.js
Labels: hacktoberfest-accepted

#8 Tree Traversal Algorithms
  Tree-Traversal/BreadthFirstTreeTraversal.js
  Tree-Traversal/DepthFirstSearch.js
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#9 Dynamic-Programming
  Dynamic-Programming/LongestCommonSubsequence.js
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#13 conversions
  conversions/ArbitraryBase.js
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#14 FenwickTree / Binary indexed tree
  Tree-Traversal/FenwickTree.js
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#15 Kadane Algorithm
  Dynamic-Programming/KadaneAlgo.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#16 Longest valid Parenthesis Problem
  Dynamic-Programming/LongestValidParentheses.js
Labels: enhancement, hacktoberfest, hacktoberfest2022, JavaScript_DSA, hacktoberfest-accepted, javascript

#17 longest palindrome subsequence
  Dynamic-Programming/LongestPalindromicSubsequence.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#18 Longest Increasing Subsequence
  Dynamic-Programming/LongestIncreasingSubsequence.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#19 date to day conversion
  conversions/DateToDay.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#20 hex to decimal and hex to binary conversion
  conversions/HexToBinary.js
  conversions/HexToDecimal.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
